// Emits the reference SQL: the rows the app needs before anyone can use it.
//
//   node supabase/seed-reference.ts > /tmp/reference.sql
//
// Everything here is idempotent, and everything here is REAL. There is no
// invented operating data — no fake clients, no fake jobs, no fake crew. The
// forms are the questions HydroDam actually asks, generated from lib/forms.ts
// so the database and the UI can never disagree about a field key. The two
// users are the two people who exist. Crew get added from the Team screen.
//
// The automations are seeded DISARMED with no epoch. That is not caution for
// its own sake: `armed_requires_epoch` plus an epoch of "now" is the only thing
// standing between the first cron run and three thousand dormant leads.

import { ONBOARDING, QA_CHECKLIST, type FieldGroup } from "../lib/forms.ts";
import {
  ACKNOWLEDGMENT, AGREEMENT_VERSION, ESIGN_CONSENT, TERMS_OF_SALE, WARRANTY,
} from "../lib/agreement.ts";

const q = (s: string | null | undefined): string =>
  s == null ? "null" : `'${s.replace(/'/g, "''")}'`;

const arr = (items: string[]): string =>
  items.length === 0 ? "'{}'" : `array[${items.map(q).join(",")}]::text[]`;

const jsonb = (v: unknown): string => `${q(JSON.stringify(v))}::jsonb`;

const slug = (s: string): string =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");

const out: string[] = [];
const say = (s: string) => out.push(s);

say(`-- Generated by supabase/seed-reference.ts. Do not edit by hand.
begin;

do $seed$
declare
  v_company uuid;
  v_template uuid;
  v_version uuid;
  v_group uuid;
begin
  select id into v_company from companies where slug = 'hydrodam';
  if v_company is null then
    raise exception 'no hydrodam company row — run supabase/bootstrap.sql first';
  end if;
`);

// ---------------------------------------------------------------- people

type Seat = { email: string; name: string; role: "owner" | "office"; color: string };

const SEATS: Seat[] = [
  { email: "info@thehydrodam.com", name: "Madeline Scribner", role: "owner", color: "#1f8ab3" },
  { email: "emma.scribner@thehydrodam.com", name: "Emma Scribner", role: "office", color: "#7eabb9" },
];

say(`  -- The two seats that exist today. Crew are added from /team.`);
for (const s of SEATS) {
  say(`  insert into users (company_id, email, full_name, role, color, is_active)
  values (v_company, ${q(s.email)}, ${q(s.name)}, ${q(s.role)}::staff_role, ${q(s.color)}, true)
  on conflict (company_id, email) do update set full_name = excluded.full_name, role = excluded.role;`);
}

// ---------------------------------------------------------------- price book

type Product = {
  sku: string; name: string; series?: "sentinel" | "onyx" | "titanium";
  unit: string; price: number; cost: number; rateSqft?: number;
  quoteOnly?: boolean; labor?: boolean;
};

// Ported from the marketing site's estimator so a quote and the public
// calculator cannot quote the same opening differently. Still the provisional
// rates — Mady has not confirmed a final $/sqft.
const PRODUCTS: Product[] = [
  { sku: "SENTINEL-SQFT", name: "Sentinel barrier", series: "sentinel", unit: "sqft", price: 5800, cost: 2600, rateSqft: 5800 },
  { sku: "ONYX-SQFT", name: "Onyx barrier", series: "onyx", unit: "sqft", price: 7200, cost: 3300, rateSqft: 7200 },
  { sku: "TITANIUM-SQFT", name: "Titanium barrier", series: "titanium", unit: "sqft", price: 9600, cost: 4500, rateSqft: 9600, quoteOnly: true },
  { sku: "POST", name: "Support post", unit: "each", price: 24000, cost: 9800 },
  { sku: "DEPLOY-KIT", name: "Deployment kit", unit: "each", price: 9500, cost: 3400 },
  { sku: "INSTALL", name: "Installation labor", unit: "opening", price: 18500, cost: 9000, labor: true },
];

say(`
  -- Price book. Provisional rates, shared with the marketing estimator.`);
for (const p of PRODUCTS) {
  say(`  insert into products (company_id, sku, name, series, unit, unit_price_cents, unit_cost_cents, rate_per_sqft_cents, quote_only, is_labor)
  values (v_company, ${q(p.sku)}, ${q(p.name)}, ${p.series ? `${q(p.series)}::product_series` : "null"}, ${q(p.unit)}, ${p.price}, ${p.cost}, ${p.rateSqft ?? "null"}, ${p.quoteOnly ?? false}, ${p.labor ?? false})
  on conflict (company_id, sku) do update set
    name = excluded.name, unit_price_cents = excluded.unit_price_cents,
    unit_cost_cents = excluded.unit_cost_cents, rate_per_sqft_cents = excluded.rate_per_sqft_cents;`);
}

// ---------------------------------------------------------------- forms

// The three checklist answers that are also as-built facts about the opening.
const MAPS_TO: Record<string, string> = {
  measured_width: "job_openings.measured_width_in",
  measured_height: "job_openings.measured_height_in",
  centre_post: "job_openings.center_post_fitted",
};

function emitForm(key: string, name: string, audience: "client" | "crew", groups: FieldGroup[]) {
  say(`
  -- ${name}
  insert into form_templates (company_id, key, name, audience)
  values (v_company, ${q(key)}, ${q(name)}, ${q(audience)})
  on conflict (company_id, key) do update set name = excluded.name
  returning id into v_template;

  insert into form_versions (company_id, template_id, version, published_at)
  values (v_company, v_template, 1, now())
  on conflict (template_id, version) do update set published_at = coalesce(form_versions.published_at, now())
  returning id into v_version;`);

  groups.forEach((g, gi) => {
    const gkey = slug(g.title);
    say(`
  insert into form_groups (company_id, version_id, key, title, blurb, sort_order)
  values (v_company, v_version, ${q(gkey)}, ${q(g.title)}, ${q(g.blurb)}, ${gi})
  on conflict (version_id, key) do update set title = excluded.title, sort_order = excluded.sort_order
  returning id into v_group;`);

    g.fields.forEach((f, fi) => {
      say(`  insert into form_fields (company_id, version_id, group_id, key, label, type, options, required, help, maps_to, sort_order)
  values (v_company, v_version, v_group, ${q(f.id)}, ${q(f.label)}, ${q(f.type)}::field_type, ${arr(f.options ?? [])}, ${f.required ?? false}, ${q(f.help)}, ${q(MAPS_TO[f.id])}, ${gi * 100 + fi})
  on conflict (version_id, key) do update set
    label = excluded.label, type = excluded.type, options = excluded.options,
    required = excluded.required, help = excluded.help, group_id = excluded.group_id,
    sort_order = excluded.sort_order;`);
    });
  });
}

emitForm("onboarding", "Customer onboarding Q&A", "client", ONBOARDING);
emitForm("qa_checklist", "Installation QA checklist", "crew", QA_CHECKLIST);

// ---------------------------------------------------------------- agreement

say(`
  -- The 5-year warranty and purchase agreement, verbatim from Mady's PDF.
  insert into agreement_templates (
    company_id, version, effective_from, title, warranty_clauses, terms_clauses,
    acknowledgment_text, esign_consent_text
  ) values (
    v_company, ${q(AGREEMENT_VERSION)}, ${q(AGREEMENT_VERSION)}::date,
    'HydroDam 5-Year Limited Warranty and Purchase Agreement',
    ${jsonb(WARRANTY)}, ${jsonb(TERMS_OF_SALE)}, ${q(ACKNOWLEDGMENT)}, ${q(ESIGN_CONSENT)}
  )
  on conflict (company_id, version) do update set
    warranty_clauses = excluded.warranty_clauses,
    terms_clauses = excluded.terms_clauses,
    acknowledgment_text = excluded.acknowledgment_text,
    esign_consent_text = excluded.esign_consent_text;`);

// ---------------------------------------------------------------- automations

type Auto = {
  id: string; name: string; trigger: string; channels: ("sms" | "email")[];
  offsets: number[]; max: number; consent?: "sms_marketing" | "email_marketing";
};

const AUTOMATIONS: Auto[] = [
  { id: "speed_to_lead", name: "Speed to lead", trigger: "request.created", channels: ["sms", "email"], offsets: [0], max: 200 },
  { id: "reminder_24h", name: "Appointment reminder — 24h", trigger: "visit.scheduled", channels: ["sms", "email"], offsets: [-1], max: 200 },
  { id: "on_my_way", name: "On my way", trigger: "visit.en_route", channels: ["sms"], offsets: [0], max: 200 },
  { id: "quote_followup", name: "Quote follow-up", trigger: "quote.sent", channels: ["email", "sms"], offsets: [3, 7, 14], max: 25 },
  { id: "invoice_reminders", name: "Invoice reminders", trigger: "invoice.sent", channels: ["email", "sms"], offsets: [-3, 0, 7, 14, 30], max: 100 },
  { id: "review_request", name: "Review request", trigger: "job.closed", channels: ["email", "sms"], offsets: [7], max: 25 },
  { id: "dormant_nurture", name: "Dormant lead nurture", trigger: "lead.status_changed", channels: ["email"], offsets: [14, 28, 42, 56], max: 25, consent: "email_marketing" },
  { id: "storm_surge", name: "Storm-watch surge alert", trigger: "manual", channels: ["email", "sms"], offsets: [0], max: 25, consent: "sms_marketing" },
];

say(`
  -- Every automation disarmed with a null epoch. Arming is an owner decision
  -- and stamps the epoch at that moment, so nothing older can ever be swept up.`);
for (const a of AUTOMATIONS) {
  say(`  insert into automation_config (company_id, automation_id, name, trigger_event, armed, epoch_at, max_sends_per_run, offsets_days, channels, requires_consent)
  values (v_company, ${q(a.id)}, ${q(a.name)}, ${q(a.trigger)}, false, null, ${a.max}, '{${a.offsets.join(",")}}'::integer[], '{${a.channels.join(",")}}'::msg_channel[], ${a.consent ? `${q(a.consent)}::consent_channel` : "null"})
  on conflict (company_id, automation_id) do update set
    name = excluded.name, trigger_event = excluded.trigger_event,
    max_sends_per_run = excluded.max_sends_per_run, offsets_days = excluded.offsets_days,
    channels = excluded.channels, requires_consent = excluded.requires_consent;`);
}

say(`
end $seed$;

commit;`);

process.stdout.write(out.join("\n") + "\n");
